# Generated by Django 3.0.8 on 2022-09-06 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220906_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='color',
            field=models.CharField(blank=True, default='#000000', max_length=7),
        ),
    ]
