# Generated by Django 3.0.8 on 2022-11-08 15:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20221108_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='Improvement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.IntegerField(max_length=10)),
                ('initial_sentence', models.CharField(max_length=500)),
                ('trans_sentence', models.CharField(max_length=500)),
                ('request_sentence', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='request',
            name='like_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='like_request', to=settings.AUTH_USER_MODEL),
        ),
    ]
