# Generated by Django 3.0.8 on 2022-11-08 15:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20221108_1515'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Improvement',
        ),
        migrations.DeleteModel(
            name='KDictionary',
        ),
        migrations.AlterField(
            model_name='request',
            name='like_users',
            field=models.ManyToManyField(blank=True, default='', related_name='like_request', to=settings.AUTH_USER_MODEL),
        ),
    ]
