# Generated by Django 3.0.8 on 2022-11-08 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20221108_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='Improvement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.IntegerField()),
                ('initial_sentence', models.CharField(max_length=500)),
                ('trans_sentence', models.CharField(max_length=500)),
                ('request_sentence', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_improvement', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
